const QUESTIONS = [
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "Je ______ à Bruxelles.",
    options: ["habite", "habites", "habitent"],
    answer: 0,
    explanation: "Avec je, les verbes en -er prennent -e : j’habite.",
  },
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "Tu ______ une maison.",
    options: ["achète", "achètes", "achetez"],
    answer: 1,
    explanation: "Avec tu, les verbes en -er prennent -es : tu achètes.",
  },
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "Il ______ de la pizza.",
    options: ["manges", "mangeons", "mange"],
    answer: 2,
    explanation: "Avec il/elle/on, les verbes en -er prennent -e : il mange.",
  },
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "Elle ______ sa famille.",
    options: ["aime", "aimes", "aiment"],
    answer: 0,
    explanation: "Avec elle, on utilise la terminaison -e : elle aime.",
  },
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "Nous ______ en France en mars.",
    options: ["voyagez", "voyagent", "voyageons"],
    answer: 2,
    explanation: "Avec nous, les verbes en -er prennent -ons : nous voyageons.",
  },
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "Vous ______ à 8 heures.",
    options: ["arrivez", "arrivons", "arrivent"],
    answer: 0,
    explanation: "Avec vous, les verbes en -er prennent -ez : vous arrivez.",
  },
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "Ils ______ le portugais.",
    options: ["étudiez", "étudient", "étudie"],
    answer: 1,
    explanation:
      "Avec ils/elles, les verbes en -er prennent -ent : ils étudient.",
  },
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "Elles ______ à un jeu.",
    options: ["joue", "jouez", "jouent"],
    answer: 2,
    explanation: "Avec elles, on utilise la terminaison -ent : elles jouent.",
  },
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "On ______ à l’église.",
    options: ["chante", "chantons", "chantent"],
    answer: 0,
    explanation: "Avec on, on conjugue comme il/elle : on chante.",
  },
  {
    type: "Affirmatif",
    title: "Complète la phrase",
    text: "J’______ de la musique le soir.",
    options: ["écoutes", "écoute", "écoutent"],
    answer: 1,
    explanation: "Devant une voyelle ou un h muet, je devient j’ : j’écoute.",
  },

  {
    type: "Négatif",
    title: "Complète la phrase négative",
    text: "Je ______ avec mes voisins.",
    options: ["ne parle", "parle pas", "ne parle pas"],
    answer: 2,
    explanation:
      "La négation se forme avec ne + verbe + pas : je ne parle pas.",
  },
  {
    type: "Négatif",
    title: "Complète la phrase négative",
    text: "Tu ______ de la guitare.",
    options: ["ne joues pas", "ne joue pas", "ne jouez pas"],
    answer: 0,
    explanation: "Avec tu, on utilise -es : tu ne joues pas.",
  },
  {
    type: "Négatif",
    title: "Complète la phrase négative",
    text: "Il ______ le livre aujourd’hui.",
    options: ["ne termines pas", "ne termine pas", "ne terminent pas"],
    answer: 1,
    explanation: "Avec il, on utilise -e : il ne termine pas.",
  },
  {
    type: "Négatif",
    title: "Complète la phrase négative",
    text: "Elle ______ le matin.",
    options: ["ne travaillent pas", "ne travaillez pas", "ne travaille pas"],
    answer: 2,
    explanation: "Avec elle, on utilise -e : elle ne travaille pas.",
  },
  {
    type: "Négatif",
    title: "Complète la phrase négative",
    text: "Nous ______ travailler le lundi.",
    options: ["ne détestons pas", "ne détestez pas", "ne détestent pas"],
    answer: 0,
    explanation: "Avec nous, on utilise -ons : nous ne détestons pas.",
  },
  {
    type: "Négatif",
    title: "Complète la phrase négative",
    text: "Vous ______ très bien.",
    options: ["ne cuisinons pas", "ne cuisinez pas", "ne cuisinent pas"],
    answer: 1,
    explanation: "Avec vous, on utilise -ez : vous ne cuisinez pas.",
  },
  {
    type: "Négatif",
    title: "Complète la phrase négative",
    text: "Ils ______ la télé le dimanche.",
    options: ["ne regardez pas", "ne regarde pas", "ne regardent pas"],
    answer: 2,
    explanation: "Avec ils/elles, on utilise -ent : ils ne regardent pas.",
  },

  {
    type: "Habiter",
    title: "Choisis la bonne préposition",
    text: "Elle habite ______ Brésil.",
    options: ["en", "chez", "au", "aux"],
    answer: 2,
    explanation: "On dit : habiter au Brésil.",
  },
  {
    type: "Habiter",
    title: "Choisis la bonne préposition",
    text: "Mon oncle et ma tante habitent ______ Belgique.",
    options: ["en", "au", "aux", "chez"],
    answer: 0,
    explanation: "On dit : habiter en Belgique.",
  },
  {
    type: "Habiter",
    title: "Choisis la bonne préposition",
    text: "Ils habitent ______ États-Unis.",
    options: ["au", "aux", "en", "chez"],
    answer: 1,
    explanation: "On dit : habiter aux États-Unis.",
  },
  {
    type: "Habiter",
    title: "Choisis la bonne préposition",
    text: "Ma sœur habite ______ un grand appartement.",
    options: ["aux", "chez", "dans", "au"],
    answer: 2,
    explanation:
      "Pour parler du type de logement, on peut dire : habiter dans un appartement.",
  },
  {
    type: "Habiter",
    title: "Choisis la bonne préposition",
    text: "Mes parents habitent ______ nous.",
    options: ["dans", "en", "chez", "aux"],
    answer: 2,
    explanation:
      "Chez = dans la maison d’une personne : mes parents habitent chez nous.",
  },

  {
    type: "Pronoms toniques",
    title: "Complète avec un pronom tonique",
    text: "Je parle avec ______.",
    options: ["tu", "te", "toi"],
    answer: 2,
    explanation:
      "Après une préposition, on utilise un pronom tonique : avec toi.",
  },
  {
    type: "Pronoms toniques",
    title: "Complète avec un pronom tonique",
    text: "Nous étudions avec ______.",
    options: ["vous", "tu", "ils"],
    answer: 0,
    explanation:
      "Après une préposition, on utilise un pronom tonique : avec vous.",
  },
  {
    type: "Pronoms toniques",
    title: "Complète avec un pronom tonique",
    text: "Je parle d’______.",
    options: ["la", "elle", "sa"],
    answer: 1,
    explanation: "Après de/d’, on utilise un pronom tonique : je parle d’elle.",
  },

  {
    type: "Interrogatif",
    title: "Choisis la question familière",
    text: "Parler avec tes amis",
    options: [
      "Tu aimes parler avec tes amis ?",
      "Est-ce que tu aimes parler avec tes amis ?",
      "Aimes-tu parler avec tes amis ?",
    ],
    answer: 0,
    explanation:
      "La question familière garde l’ordre sujet + verbe : tu aimes... ?",
  },
  {
    type: "Interrogatif",
    title: "Choisis la question courante",
    text: "Une maison",
    options: [
      "Tu achètes une maison ?",
      "Est-ce que tu achètes une maison ?",
      "Achètes-tu une maison ?",
    ],
    answer: 1,
    explanation:
      "La forme courante utilise est-ce que : est-ce que tu achètes... ?",
  },
  {
    type: "Interrogatif",
    title: "Choisis la question formelle",
    text: "De la pizza",
    options: [
      "Il mange de la pizza ?",
      "Est-ce qu’il mange de la pizza ?",
      "Mange-t-il de la pizza ?",
    ],
    answer: 2,
    explanation: "À la 3e personne du singulier, on ajoute -t- : mange-t-il.",
  },
  {
    type: "Interrogatif",
    title: "Choisis la question courante",
    text: "Le matin",
    options: [
      "Est-ce qu’elle travaille le matin ?",
      "Travaille-t-elle le matin ?",
      "Elle travaille le matin ?",
    ],
    answer: 0,
    explanation: "La forme courante utilise est-ce que.",
  },
  {
    type: "Interrogatif",
    title: "Change la question",
    text: "Qu’écoutes-tu ?",
    options: ["Tu écoutes que ?", "Quoi écoutes-tu ?", "Tu écoutes quoi ?"],
    answer: 2,
    explanation:
      "En langage familier, on met souvent quoi à la fin : tu écoutes quoi ?",
  },

  {
    type: "Défi final",
    title: "Case 30",
    text: "Transforme en question formelle : Il habite à Londres.",
    options: [
      "Habite-il à Londres ?",
      "Habite-t-il à Londres ?",
      "Est-ce qu’il habite à Londres ?",
    ],
    answer: 1,
    explanation: "La forme formelle est : Habite-t-il à Londres ?",
  },

  {
    type: "Défi chrono",
    title: "Défi chrono",
    text: "Tu as 15 secondes : complète « J’______ de la musique. »",
    options: ["écoutes", "écoute", "écoutent"],
    answer: 1,
    explanation: "Devant une voyelle, je devient j’ : j’écoute.",
    timed: true,
  },
  {
    type: "Défi chrono",
    title: "Défi chrono",
    text: "Tu as 15 secondes : choisis la bonne phrase.",
    options: [
      "Elle ne aime pas les oiseaux.",
      "Elle n’aime pas les oiseaux.",
      "Elle n’aimes pas les oiseaux.",
    ],
    answer: 1,
    explanation: "La bonne phrase est : elle n’aime pas les oiseaux.",
    timed: true,
  },
  {
    type: "Défi chrono",
    title: "Défi chrono",
    text: "Tu as 15 secondes : choisis la question formelle.",
    options: [
      "Termine-il le livre aujourd’hui ?",
      "Il termine le livre aujourd’hui ?",
      "Termine-t-il le livre aujourd’hui ?",
    ],
    answer: 2,
    explanation: "On ajoute -t- : termine-t-il.",
    timed: true,
  },
];
